### ISSUE TITLE
No module named `pkg_resources`

### ISSUE THREAD

**Issue by DeadNews** [ansible/ansible-dev-environment#122]
## Description

When running `poetry run ade install -r requirements.yml`, the command fails with a `ModuleNotFoundError: No module named 'pkg_resources'`.

```console
$ poetry run ade install -r requirements.yml
Failed to discover requirements: Command 'ansible-builder introspect /home/runner/.cache/pypoetry/virtualenvs/deadnews-template-ansible-kPNM4ADQ-py3.12/lib/python3.12/site-packages --write-pip /home/runner/.cache/pypoetry/virtualenvs/deadnews-template-ansible-kPNM4ADQ-py3.12/.ansible-dev-environment/discovered_requirements.txt --write-bindep /home/runner/.cache/pypoetry/virtualenvs/deadnews-template-ansible-kPNM4ADQ-py3.12/.ansible-dev-environment/discovered_bindep.txt --sanitize' returned non-zero exit status 1. ModuleNotFoundError: No module named 'pkg_resources'
```

## Possible solution

The `pkg_resources` module is part of `setuptools`.

According to the [Poetry documentation](https://python-poetry.org/docs/configuration/#virtualenvsoptionsno-setuptools):
> If your project relies on `setuptools`, you should declare it as a dependency.

## Context

[GitHub workflow log](https://github.com/DeadNews/deadnews-template-ansible/actions/runs/8314015419/job/22750669499?pr=97#step:6:14).

```console
$ ade --version
24.1.0
```

**Comment by ssbarnea** [comment]
This is not a bug within ade tool. While we do try to import pkg_resources, we nicely ignore an import failure. Poetry use is also not supported, so please identify the tool that generates the exception and try to propose a fix for it.
