### ISSUE TITLE
Add `--user` and `--system` flag to allow for use of the user/system sitepkgs directory instead of venv

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-dev-environment#123]
This will help with use of the dev container, the alternate user/system should still be checked to ensure python deps are resolved correctly.

In the case of an EE, we may allow for installation of collection into user site packages and assume collections install in the system ansible path have already had thei python deps resolved and just ignor them...

Related #27

**Comment by ssbarnea** [comment]
Closing as there are no current plans on adding this yet.
